/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CitizenOrganisationRole;

import Business.Enterprise.Enterprise;
import Business.Organization.CitizenOrganisation;
import Business.Organization.PollutionDeterminingDeptOrganisation;
import Business.UserAccount.UserAccount;
import com.teamdev.jxbrowser.chromium.Browser;
import com.teamdev.jxbrowser.chromium.swing.BrowserView;
import com.teknikindustries.yahooweather.WeatherDisplay;
import com.teknikindustries.yahooweather.WeatherDoc;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.WindowConstants;

/**
 *
 * @author DeepaliP
 */
public class CitizenOrganisationWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CitizenOrganisationWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private CitizenOrganisation organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private String a;

    public CitizenOrganisationWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, CitizenOrganisation organization, Enterprise enterprise) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        valueLabel.setText(enterprise.getName());
        showPollutionLevel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        btnShowMaps = new javax.swing.JButton();
        comboList = new javax.swing.JComboBox();
        lblWeather1 = new javax.swing.JLabel();
        lblWeather2 = new javax.swing.JLabel();
        lblWeather5 = new javax.swing.JLabel();
        lblWeather6 = new javax.swing.JLabel();
        txtTemperature = new javax.swing.JTextField();
        txtCondition = new javax.swing.JTextField();
        txtHumidity = new javax.swing.JTextField();
        txtVisibility = new javax.swing.JTextField();
        txtPressure = new javax.swing.JTextField();
        lblWeather7 = new javax.swing.JLabel();
        txtPollution = new javax.swing.JTextField();
        lblWeather3 = new javax.swing.JLabel();
        txtWindChill = new javax.swing.JLabel();
        txtWindDirection = new javax.swing.JLabel();
        txtTemperature1 = new javax.swing.JTextField();
        txtCondition1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblWeather4 = new javax.swing.JLabel();
        txtWindSpeed1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseLabel.setBackground(new java.awt.Color(204, 204, 255));
        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("ENTERPRISE :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 76, 150, 40));

        valueLabel.setBackground(new java.awt.Color(204, 204, 255));
        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 76, 150, 40));

        btnShowMaps.setBackground(new java.awt.Color(204, 204, 255));
        btnShowMaps.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnShowMaps.setText("SHOW MAPS");
        btnShowMaps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowMapsActionPerformed(evt);
            }
        });
        add(btnShowMaps, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 669, 168, 30));

        comboList.setBackground(new java.awt.Color(204, 204, 255));
        comboList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Allston", "Brighton", "Fenway Kenmore", "Mission Hill", "Jamaica PlainRoxbury", "Downtown", "CharlesTown", "Back Bay", "Dorchester", "South End", "Bay Village", "South Boston", "East Boston", "Hyde Park" }));
        comboList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboListActionPerformed(evt);
            }
        });
        add(comboList, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 152, 200, 40));

        lblWeather1.setBackground(new java.awt.Color(204, 204, 255));
        lblWeather1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblWeather1.setText("HUMIDITY");
        add(lblWeather1, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 318, 168, 34));

        lblWeather2.setBackground(new java.awt.Color(204, 204, 255));
        lblWeather2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblWeather2.setText("TEMPERATURE");
        add(lblWeather2, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 220, 150, 30));

        lblWeather5.setBackground(new java.awt.Color(204, 204, 255));
        lblWeather5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblWeather5.setText("PRESSURE");
        add(lblWeather5, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 365, 168, 30));

        lblWeather6.setBackground(new java.awt.Color(204, 204, 255));
        lblWeather6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblWeather6.setText("CONDITION");
        add(lblWeather6, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 269, 168, 31));

        txtTemperature.setEditable(false);
        txtTemperature.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTemperature.setEnabled(false);
        add(txtTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 221, 146, 30));

        txtCondition.setEditable(false);
        txtCondition.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCondition.setEnabled(false);
        add(txtCondition, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 269, 146, 31));

        txtHumidity.setEditable(false);
        txtHumidity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtHumidity.setEnabled(false);
        add(txtHumidity, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 318, 146, 30));

        txtVisibility.setEditable(false);
        txtVisibility.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtVisibility.setEnabled(false);
        add(txtVisibility, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 409, 146, 30));

        txtPressure.setEditable(false);
        txtPressure.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPressure.setEnabled(false);
        add(txtPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 366, 146, 30));

        lblWeather7.setBackground(new java.awt.Color(204, 204, 255));
        lblWeather7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblWeather7.setText("VISIBILITY");
        add(lblWeather7, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 408, 168, 30));

        txtPollution.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtPollution, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 505, 146, 30));

        lblWeather3.setBackground(new java.awt.Color(204, 204, 255));
        lblWeather3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblWeather3.setText("WIND SPEED");
        add(lblWeather3, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 553, 168, 30));

        txtWindChill.setBackground(new java.awt.Color(204, 204, 255));
        txtWindChill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtWindChill.setText("WIND CHILL");
        add(txtWindChill, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 602, 168, 30));

        txtWindDirection.setBackground(new java.awt.Color(204, 204, 255));
        txtWindDirection.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtWindDirection.setText("WIND DIRECTION");
        add(txtWindDirection, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 457, 168, 30));

        txtTemperature1.setEditable(false);
        txtTemperature1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTemperature1.setEnabled(false);
        add(txtTemperature1, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 603, 146, 30));

        txtCondition1.setEditable(false);
        txtCondition1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCondition1.setEnabled(false);
        add(txtCondition1, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 457, 146, 30));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("SELECT CITY");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 152, 150, 40));

        lblWeather4.setBackground(new java.awt.Color(204, 204, 255));
        lblWeather4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblWeather4.setText("POLLUTION");
        add(lblWeather4, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 505, 168, 30));

        txtWindSpeed1.setEditable(false);
        txtWindSpeed1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtWindSpeed1.setEnabled(false);
        add(txtWindSpeed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 554, 146, 30));

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("CITIZENS WORK AREA");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 16, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/CitizenOrganisationRole/sun_rain_cc.gif"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, 330, 240));
    }// </editor-fold>//GEN-END:initComponents
 public void showPollutionLevel() {
        Random r = new Random();
        int Low = 73;
        int High = 80;

        a = String.valueOf(r.nextInt(High - Low) + Low);
     

        
    }
    private void comboListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboListActionPerformed
       
        if (comboList.getSelectedItem().equals("Allston")) {
            WeatherDoc doc1 = new WeatherDoc("2353542", "c");
            WeatherDisplay disp1 = new WeatherDisplay();
            txtTemperature.setText(disp1.getTemperature() + " " + "C");
            txtCondition.setText(disp1.getCondition());
            txtHumidity.setText(disp1.getHumidity());
            txtPressure.setText(disp1.getPressureUnit());
            txtVisibility.setText(disp1.getVisibility());
            txtTemperature1.setText(disp1.getWindChill());
            txtCondition1.setText(disp1.getWindDirection());
            txtWindSpeed1.setText(disp1.getWindSpeed());
            txtPollution.setText(a);
            if (Integer.parseInt(a) > 75) {
                txtPollution.setBackground(Color.RED);
            }

        }
        if (comboList.getSelectedItem().equals("Brighton")) {
            WeatherDoc doc1 = new WeatherDoc("2369156", "c");
            WeatherDisplay disp1 = new WeatherDisplay();
            txtTemperature.setText(disp1.getTemperature() + " " + "C");
            txtCondition.setText(disp1.getCondition());
            txtHumidity.setText(disp1.getHumidity());
            txtPressure.setText(disp1.getPressureUnit());
            txtVisibility.setText(disp1.getVisibility());
            txtTemperature1.setText(disp1.getWindChill());
            txtCondition1.setText(disp1.getWindDirection());
            txtWindSpeed1.setText(disp1.getWindSpeed());
            txtPollution.setText(a);
            if (Integer.parseInt(a) > 75) {
                txtPollution.setBackground(Color.RED);
            }

        }
        if (comboList.getSelectedItem().equals("Fenway Kenmore")) {
            WeatherDoc doc1 = new WeatherDoc("28751323", "c");
            WeatherDisplay disp1 = new WeatherDisplay();
            txtTemperature.setText(disp1.getTemperature() + " " + "C");
            txtCondition.setText(disp1.getCondition());
            txtHumidity.setText(disp1.getHumidity());
            txtPressure.setText(disp1.getPressureUnit());
            txtVisibility.setText(disp1.getVisibility());
            txtTemperature1.setText(disp1.getWindChill());
            txtCondition1.setText(disp1.getWindDirection());
            txtWindSpeed1.setText(disp1.getWindSpeed());
            txtPollution.setText(a);
            if (Integer.parseInt(a) > 75) {
                txtPollution.setBackground(Color.RED);
            }

        }
        if (comboList.getSelectedItem().equals("Mission Hill")) {
            WeatherDoc doc1 = new WeatherDoc("28751386", "c");
            WeatherDisplay disp1 = new WeatherDisplay();
            txtTemperature.setText(disp1.getTemperature() + " " + "C");
            txtCondition.setText(disp1.getCondition());
            txtHumidity.setText(disp1.getHumidity());
            txtPressure.setText(disp1.getPressureUnit());
            txtVisibility.setText(disp1.getVisibility());
            txtTemperature1.setText(disp1.getWindChill());
            txtCondition1.setText(disp1.getWindDirection());
            txtWindSpeed1.setText(disp1.getWindSpeed());
            txtPollution.setText(a);
            if (Integer.parseInt(a) > 75) {
                txtPollution.setBackground(Color.RED);
            }

        }
        if (comboList.getSelectedItem().equals("Jamaica PlainRoxbury")) {
            WeatherDoc doc1 = new WeatherDoc("23424858", "c");
            WeatherDisplay disp1 = new WeatherDisplay();
            txtTemperature.setText(disp1.getTemperature() + " " + "C");
            txtCondition.setText(disp1.getCondition());
            txtHumidity.setText(disp1.getHumidity());
            txtPressure.setText(disp1.getPressureUnit());
            txtVisibility.setText(disp1.getVisibility());
            txtTemperature1.setText(disp1.getWindChill());
            txtCondition1.setText(disp1.getWindDirection());
            txtWindSpeed1.setText(disp1.getWindSpeed());
            txtPollution.setText(a);
            if (Integer.parseInt(a) > 75) {
                txtPollution.setBackground(Color.RED);
            }

        }
        if (comboList.getSelectedItem().equals("Downtown")) {
            WeatherDoc doc1 = new WeatherDoc("2347580", "c");
            WeatherDisplay disp1 = new WeatherDisplay();
            txtTemperature.setText(disp1.getTemperature() + " " + "C");
            txtCondition.setText(disp1.getCondition());
            txtHumidity.setText(disp1.getHumidity());
            txtPressure.setText(disp1.getPressureUnit());
            txtVisibility.setText(disp1.getVisibility());
            txtTemperature1.setText(disp1.getWindChill());
            txtCondition1.setText(disp1.getWindDirection());
            txtWindSpeed1.setText(disp1.getWindSpeed());
            txtPollution.setText(a);
            if (Integer.parseInt(a) > 75) {
                txtPollution.setBackground(Color.RED);
            }

        }
        if (comboList.getSelectedItem().equals("CharlesTown")) {
            WeatherDoc doc1 = new WeatherDoc("2378387", "c");
            WeatherDisplay disp1 = new WeatherDisplay();
            txtTemperature.setText(disp1.getTemperature() + " " + "C");
            txtCondition.setText(disp1.getCondition());
            txtHumidity.setText(disp1.getHumidity());
            txtPressure.setText(disp1.getPressureUnit());
            txtVisibility.setText(disp1.getVisibility());
            txtTemperature1.setText(disp1.getWindChill());
            txtCondition1.setText(disp1.getWindDirection());
            txtWindSpeed1.setText(disp1.getWindSpeed());
            txtPollution.setText(a);
            if (Integer.parseInt(a) > 75) {
                txtPollution.setBackground(Color.RED);
            }

        }
        if (comboList.getSelectedItem().equals("Back Bay")) {
            WeatherDoc doc1 = new WeatherDoc("2358123", "c");
            WeatherDisplay disp1 = new WeatherDisplay();
            txtTemperature.setText(disp1.getTemperature() + " " + "C");
            txtCondition.setText(disp1.getCondition());
            txtHumidity.setText(disp1.getHumidity());
            txtPressure.setText(disp1.getPressureUnit());
            txtVisibility.setText(disp1.getVisibility());
            txtTemperature1.setText(disp1.getWindChill());
            txtCondition1.setText(disp1.getWindDirection());
            txtWindSpeed1.setText(disp1.getWindSpeed());
            txtPollution.setText(a);
            if (Integer.parseInt(a) > 75) {
                txtPollution.setBackground(Color.RED);
            }

        }
        if (comboList.getSelectedItem().equals("Dorchester")) {
            WeatherDoc doc1 = new WeatherDoc("2392994", "c");
            WeatherDisplay disp1 = new WeatherDisplay();
            txtTemperature.setText(disp1.getTemperature() + " " + "C");
            txtCondition.setText(disp1.getCondition());
            txtHumidity.setText(disp1.getHumidity());
            txtPressure.setText(disp1.getPressureUnit());
            txtVisibility.setText(disp1.getVisibility());
            txtTemperature1.setText(disp1.getWindChill());
            txtCondition1.setText(disp1.getWindDirection());
            txtWindSpeed1.setText(disp1.getWindSpeed());
            txtPollution.setText(a);
            if (Integer.parseInt(a) > 75) {
                txtPollution.setBackground(Color.RED);
            }

        }
        if (comboList.getSelectedItem().equals("South End")) {
            WeatherDoc doc1 = new WeatherDoc("28751488", "c");
            WeatherDisplay disp1 = new WeatherDisplay();
            txtTemperature.setText(disp1.getTemperature() + " " + "C");
            txtCondition.setText(disp1.getCondition());
            txtHumidity.setText(disp1.getHumidity());
            txtPressure.setText(disp1.getPressureUnit());
            txtVisibility.setText(disp1.getVisibility());
            txtTemperature1.setText(disp1.getWindChill());
            txtCondition1.setText(disp1.getWindDirection());
            txtWindSpeed1.setText(disp1.getWindSpeed());
            txtPollution.setText(a);
            if (Integer.parseInt(a) > 75) {
                txtPollution.setBackground(Color.RED);
            }

        }
        if (comboList.getSelectedItem().equals("Bay Village")) {
            WeatherDoc doc1 = new WeatherDoc("28751163", "c");
            WeatherDisplay disp1 = new WeatherDisplay();
            txtTemperature.setText(disp1.getTemperature() + " " + "C");
            txtCondition.setText(disp1.getCondition());
            txtHumidity.setText(disp1.getHumidity());
            txtPressure.setText(disp1.getPressureUnit());
            txtVisibility.setText(disp1.getVisibility());
            txtTemperature1.setText(disp1.getWindChill());
            txtCondition1.setText(disp1.getWindDirection());
            txtWindSpeed1.setText(disp1.getWindSpeed());
            txtPollution.setText(a);
            if (Integer.parseInt(a) > 75) {
                txtPollution.setBackground(Color.RED);
            }

        }
        if (comboList.getSelectedItem().equals("South Boston")) {
            WeatherDoc doc1 = new WeatherDoc("2496012", "c");
            WeatherDisplay disp1 = new WeatherDisplay();
            txtTemperature.setText(disp1.getTemperature() + " " + "C");
            txtCondition.setText(disp1.getCondition());
            txtHumidity.setText(disp1.getHumidity());
            txtPressure.setText(disp1.getPressureUnit());
            txtVisibility.setText(disp1.getVisibility());
            txtTemperature1.setText(disp1.getWindChill());
            txtCondition1.setText(disp1.getWindDirection());
            txtWindSpeed1.setText(disp1.getWindSpeed());
            txtPollution.setText(a);
            if (Integer.parseInt(a) > 75) {
                txtPollution.setBackground(Color.RED);
            }

        }
        if (comboList.getSelectedItem().equals("East Boston")) {
            WeatherDoc doc1 = new WeatherDoc("2395356", "c");
            WeatherDisplay disp1 = new WeatherDisplay();
            txtTemperature.setText(disp1.getTemperature() + " " + "C");
            txtCondition.setText(disp1.getCondition());
            txtHumidity.setText(disp1.getHumidity());
            txtPressure.setText(disp1.getPressureUnit());
            txtVisibility.setText(disp1.getVisibility());
            txtTemperature1.setText(disp1.getWindChill());
            txtCondition1.setText(disp1.getWindDirection());
            txtWindSpeed1.setText(disp1.getWindSpeed());
            txtPollution.setText(a);
            if (Integer.parseInt(a) > 75) {
                txtPollution.setBackground(Color.RED);
            }

        }
        if (comboList.getSelectedItem().equals("Hyde Park")) {
            WeatherDoc doc1 = new WeatherDoc("2426308", "c");
            WeatherDisplay disp1 = new WeatherDisplay();
            txtTemperature.setText(disp1.getTemperature() + " " + "C");
            txtCondition.setText(disp1.getCondition());
            txtHumidity.setText(disp1.getHumidity());
            txtPressure.setText(disp1.getPressureUnit());
            txtVisibility.setText(disp1.getVisibility());
            txtTemperature1.setText(disp1.getWindChill());
            txtCondition1.setText(disp1.getWindDirection());
            txtWindSpeed1.setText(disp1.getWindSpeed());
            txtPollution.setText(a);
            if (Integer.parseInt(a) > 75) {
                txtPollution.setBackground(Color.RED);
            }

        }


    }//GEN-LAST:event_comboListActionPerformed

    private void btnShowMapsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowMapsActionPerformed
        final Browser browser = new Browser();
        BrowserView browserView = new BrowserView(browser);

        JFrame frame = new JFrame("Google Maps");
        frame.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
        frame.add(browserView, BorderLayout.CENTER);
        frame.setSize(900, 500);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);

        browser.loadURL("http://maps.google.com/");

    }//GEN-LAST:event_btnShowMapsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShowMaps;
    private javax.swing.JComboBox comboList;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblWeather1;
    private javax.swing.JLabel lblWeather2;
    private javax.swing.JLabel lblWeather3;
    private javax.swing.JLabel lblWeather4;
    private javax.swing.JLabel lblWeather5;
    private javax.swing.JLabel lblWeather6;
    private javax.swing.JLabel lblWeather7;
    private javax.swing.JTextField txtCondition;
    private javax.swing.JTextField txtCondition1;
    private javax.swing.JTextField txtHumidity;
    private javax.swing.JTextField txtPollution;
    private javax.swing.JTextField txtPressure;
    private javax.swing.JTextField txtTemperature;
    private javax.swing.JTextField txtTemperature1;
    private javax.swing.JTextField txtVisibility;
    private javax.swing.JLabel txtWindChill;
    private javax.swing.JLabel txtWindDirection;
    private javax.swing.JTextField txtWindSpeed1;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
