/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PollutionDeterminingDeptRole;

import userinterface.RegularMaintainanceDeptRole.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.CitizenOrganisation;
import Business.Organization.Citizens;
import Business.Organization.Organization;
import Business.Organization.PollutionDeterminingDeptOrganisation;
import Business.Organization.RegularMaintainanceDeptOrganisation;
import Business.Organization.TraficControlRoomOrganisation;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.PollutionDeterDeptToTrafficControl;
import Business.WorkQueue.RegularMaintainanceToTrafficControl;
import Business.WorkQueue.TrafficCityArrayListClass;
import Business.WorkQueue.TrafficDeterToPollutionDeterDept;

import Business.WorkQueue.WorkRequest;
import static com.sun.corba.se.spi.presentation.rmi.StubAdapter.request;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import static userinterface.PollutionDeterminingDeptRole.MailSender.emailBody;
import static userinterface.PollutionDeterminingDeptRole.MailSender.emailSubject;

/**
 *
 * @author DeepaliP
 */
public class PollutionDeterminingDeptWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private PollutionDeterminingDeptOrganisation organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private ArrayList<String> list1;
    private ArrayList<Integer> list2;
    private ArrayList<Integer> list3;
    private ArrayList<String> list4;
    private TrafficDeterToPollutionDeterDept req;

    /**
     * Creates new form PollutionDeterminingDeptWorkAreaJPanel
     */
    public PollutionDeterminingDeptWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, PollutionDeterminingDeptOrganisation organization, Enterprise enterprise) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        valueLabel.setText(enterprise.getName());
        list3 = new ArrayList<Integer>();
        list4 = new ArrayList<String>();
        populateRequestTable();
    }

    public void populateRequestTable() {
        list1 = new ArrayList<String>();
        list2 = new ArrayList<Integer>();
        //list3 = new ArrayList<Integer>();

        DefaultTableModel model = (DefaultTableModel) tblPollutionDetermination.getModel();

        Random r = new Random();
        int Low = 0;
        int High = 5;

        model.setRowCount(0);

        for (Organization oz : enterprise.getOrganizationDirectory().getOrganizationList()) {

            for (TrafficCityArrayListClass tc : oz.getTrafficCityArrayList().getTrafficCityArrayList()) {

                list1 = tc.getList1();
                list2 = tc.getList2();
            }
        }
        for (WorkRequest req1 : organization.getWorkQueue().getWorkRequestList()) {

            // list3.addAll(((TrafficDeterToPollutionDeterDept) req1).getListt1());
            for (int i = 0; i < list1.size(); i++) {

                Object[] row = new Object[6];
                row[0] = list1.get(i);
                row[1] = r.nextInt(High - Low) + Low;
                row[2] = r.nextInt(High - Low) + Low;
                row[3] = r.nextInt(High - Low) + Low;
                row[4] = list2.get(i);
                row[5] = (int) row[1] + (int) row[2] + (int) row[3] + (int) row[4];

                model.addRow(row);

            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        btnSendRequest = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPollutionDetermination = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnSendEmail = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("ENTERPRISE");

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnSendRequest.setBackground(new java.awt.Color(204, 204, 255));
        btnSendRequest.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSendRequest.setText("SEND INFORMATION");
        btnSendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendRequestActionPerformed(evt);
            }
        });

        tblPollutionDetermination.setBackground(new java.awt.Color(204, 204, 255));
        tblPollutionDetermination.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblPollutionDetermination.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "City", "Carbon monoxide (CO) ", "Oxides of nitrogen (NOx)", "Sulphur dioxide", "Traffic", "Pollution In Air"
            }
        ));
        jScrollPane1.setViewportView(tblPollutionDetermination);

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("POLLUTION DETERMINING DEPT");

        btnSendEmail.setBackground(new java.awt.Color(204, 204, 255));
        btnSendEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSendEmail.setText("SEND EMAIL");
        btnSendEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSendRequest)
                        .addGap(66, 66, 66)
                        .addComponent(btnSendEmail)
                        .addGap(493, 493, 493))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1058, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 327, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSendRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(128, 128, 128))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(212, 212, 212)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(204, Short.MAX_VALUE)))
        );

        jLabel2.getAccessibleContext().setAccessibleName("pOLLUTION DETERMINING DEPT");
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendRequestActionPerformed

        PollutionDeterDeptToTrafficControl req1 = new PollutionDeterDeptToTrafficControl();
        req1.setMessage("Message");
        req1.setSender(userAccount);
        req1.setStatus("Sent");

        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof TraficControlRoomOrganisation) {
                org = organization;
                break;
            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(req1);
            userAccount.getWorkQueue().getWorkRequestList().add(req1);
        }
        JOptionPane.showMessageDialog(null, "Information Sent Successfully To control Dept");
    }//GEN-LAST:event_btnSendRequestActionPerformed

    private void btnSendEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendEmailActionPerformed
        CitizenOrganisation ho;

        for (Organization or : enterprise.getOrganizationDirectory().getOrganizationList()) {

            if (or instanceof CitizenOrganisation) {
                ho = (CitizenOrganisation) or;
                for (Citizens c : ho.cD.getCitizensdirectory()) {
                    list4.add(c.getEmail_id());
                    //tele_no= new String[organ.getCitizenDirectory().getCitizensdirectory().size()];
                }
                String email_id[] = new String[list4.size()];

                for (int k = 0; k < list4.size(); k++) {

                    email_id[k] = list4.get(k);
                    userinterface.TraficManagementPatrolRole.MailSender mailSender = new userinterface.TraficManagementPatrolRole.MailSender(email_id[k], emailSubject, emailBody);

                    JOptionPane.showMessageDialog(null, "Email Sent Successfully");
                }

            }
        }
    }//GEN-LAST:event_btnSendEmailActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendEmail;
    private javax.swing.JButton btnSendRequest;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPollutionDetermination;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
